In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [2]:
%cd gdrive/MyDrive/study/빅데이터마이닝 실습/MNIST

/content/gdrive/MyDrive/study/빅데이터마이닝 실습/MNIST


In [3]:
import sys
import os
import numpy as np
#sys.path.append('/content/gdrive/MyDrive/Colab Notebooks/MNIST')
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


In [4]:
# 4.4.2 신경망에서의 기울기
class simpleNet:
    """docstring for simpleNet"""
    def __init__(self):
        self.W = np.random.randn(2, 3)  # 정규분포로 초기화

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [13]:
net = simpleNet()
print(net.W)  # 가중치 매개변수(랜덤)
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))  # 최댓값의 인덱스

t = np.array([0, 0, 1])  # 정답 레이블
print(net.loss(x, t))


[[ 0.03002725  0.69624984 -0.3571544 ]
 [-0.33809096 -0.35205392 -0.51846129]]
[-0.28626551  0.10090137 -0.6809078 ]
1
1.5410039868942993


In [14]:
def f(W):  # 인수 W는 dummy임
    return net.loss(x, t)


dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.19067453  0.28082588 -0.47150042]
 [ 0.2860118   0.42123883 -0.70725062]]
